---
version: "3"

env:
  GOBIN: /usr/local/bin

tasks:
  default:
    desc: "Build, run tests, build examples"
    cmds:
      - task: build

  build:
    desc: "Build and install"
    cmds:
      - goimports -w -local=$(go list .) .
      - go fmt ./...
      - go mod tidy
      - go clean -cache
      - go build .
      - go install .
      - modcheck
