---
version: "3"

env:
  GOBIN: /usr/local/bin
  CGO_ENABLED: 0

tasks:
  default:
    desc: "Run default (install)"
    cmds:
      - task: install

  test:
    desc: "Run tests"
    deps: [ install ]
    cmds:
      - task: test:semgrep
      - task: test:vet
      - task: test:modfile

  test:modfile:
    desc: "Run tests for modfile"
    cmds:
      - cat go.mod | summary modfile

  test:semgrep:
    desc: "Run tests for semgrep"
    cmds:
      - cat testdata/semgrep-results.json | summary semgrep
      - cat testdata/semgrep-error.json | summary semgrep
      - cat testdata/semgrep-syntax.json | summary semgrep

  test:vet:
    desc: "Run tests for vet"
    cmds:
      - cat testdata/vet.json | summary vet
      - cat testdata/vet-analytics.json | summary vet

  build:
    desc: "Build from source"
    deps: [ fmt ]
    cmds:
      - go build .

  install:
    desc: "Install from source"
    deps: [ fmt ]
    cmds:
      - go install .

  fmt:
    internal: true
    cmds:
      - goimports -w -local=$(go list .) .
      - go fmt ./...
      - go mod tidy

  docker:
    desc: "Build docker image"
    deps: [ build ]
    vars:
      image: internal/summary
    cmds:
      - docker build -t {{.image}} .
      - docker run --rm {{.image}} -? || true
