---
name: 'GitHub Sync'
description: >
  Emit a repository_dispatch event to synchronize repositories

inputs:
  repository:
    description: 'The target repository to dispatch the event to'
    required: true
  eventType:
    description: 'The type of event to emit'
    required: true
  token:
    description: 'A GitHub Personal Access Token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Emit repository_dispatch event
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ inputs.token }}
        repository: ${{ inputs.repository }}
        event-type: ${{ inputs.eventType }}
        client-payload: '{"ref":"${{ github.ref }}", "sha":"${{ github.sha }}"}'
