---
version: "3"

# This taskfile is in use in github-actions.
# It traverses detected go packages and prints
# their `go doc` output. That is used to compare
# API changes on PRs with the godoc action.

tasks:
  default:
    desc: "Run godoc on all packages"
    vars:
      package:
        sh: go mod edit -json | jq .Module.Path -r
      packages:
        sh: go list ./... | sed -e 's|{{.package}}|.|g'
    silent: true
    cmds:
      - |
        set -e;
        {{- range $i, $package := .packages | splitLines -}}
          echo -e "# Package: {{ $package }}\n"
          go doc -all {{ $package }} || true
        {{ end -}}
