---
version: "3"

tasks:
  default:
    desc: Local test actions
    deps:
      - install:actionlint
    cmds:
      - task: lint

  lint:
    desc: Lint actions
    cmds:
      - actionlint ./workflows/tyk-docs.yml

  install:actionlint:
    desc: Install actionlint
    status:
      - type actionlint
    cmds:
      - go install github.com/rhysd/actionlint/cmd/actionlint@latest
