---
version: "3"

tasks:
  default:
    desc: "Build, test, install and run schema-gen"
    cmds:
      - go fmt ./...
      - go build .
      - go test -race -count=100 ./...
      - go install .

      - schema-gen -i model/ -o model/model.json
      - schema-gen -i example/ -o example/example.json