---
version: "3"

tasks:
  default:
    desc: "Build, test, install and run schema-gen"
    cmds:
      - goimports -w .
      - go fmt ./...
      - go build .
      - go test -race -count=100 ./...
      - go install .
      - task: examples

  examples:
    desc: "Build examples"
    silent: true
    cmds:
      - echo "Building examples:"
      - schema-gen extract -i model/ -o model/model.json
      - schema-gen restore -i model/model.json -o model/model.go.txt -p model
      - schema-gen extract -i _example/ -o _example/example.json
      - schema-gen restore -i _example/example.json -o _example/example.go.txt -p example

  help:
    desc: "Run schema gen to print usage/help"
    cmds:
      - schema-gen
      - schema-gen extract help
      - schema-gen restore help
