---
version: "3"

tasks:
  default:
    desc: "Build, run tests, build examples"
    deps: [ build ]
    cmds:
      - go test -race -count=100 ./...
      - task: examples

  build:
    desc: "Build and install schema-gen"
    cmds:
      - goimports -w .
      - go fmt ./...
      - go mod tidy
      - go clean -cache
      - go build .
      - go install .

  lint:
    desc: "Run linter tests against schema-gen model"
    deps: [ build ]
    cmds:
      - schema-gen extract -i model/ -o model/model.json
      - schema-gen markdown -i model/model.json -o model/model.md --root PackageInfo
      - schema-gen lint -i model/model.json

  examples:
    desc: "Build examples"
    silent: true
    cmds:
      - echo "Building examples:"
      - schema-gen extract -i model/ -o model/model.json
      - schema-gen markdown -i model/model.json -o model/model.md --root PackageInfo
      - schema-gen restore -i model/model.json -o model/model.go.txt -p model
      - schema-gen extract -i _example/ -o _example/example.json
      - schema-gen restore -i _example/example.json -o _example/example.go.txt -p example
      - schema-gen restore -i _example/example.json -o _example/example_file.go.txt --keep File -p example

  help:
    desc: "Run schema gen to print usage/help"
    cmds:
      - schema-gen
      - schema-gen extract help
      - schema-gen restore help
