stateDiagram-v2
    workflow : api-tests.yml - API integration Tests
    state workflow {
        test: Test
        state test {
            [*] --> step0test
            step0test : Set up Python 3.7
            step0test --> step1test
            step1test : Fix private module deps
            step1test --> step2test
            step2test : Checkout of Dashboard
            step2test --> step3test
            step3test : Check if test framework branch exists
            step3test --> step4test
            step4test : Checkout test repository
            step4test --> step5test
            step5test : Check if GW branch exists
            step5test --> step6test
            step6test : Checkout GW repository
            step6test --> step7test
            step7test : start docker compose
            step7test --> step8test
            step8test : Install test dependecies
            step8test --> step9test
            step9test : Lint with flake8
            step9test --> step10test
            step10test : Waiting for dashboard
            step10test --> step11test
            step11test : Getting dashboard logs on failure
            step11test --> step12test
            step12test : Test with pytest
            step12test --> step13test
            step13test : Archive Integration tests report
            step13test --> step14test
            step14test : Notify slack
            step14test --> step15test
            step15test : Comment on PR
            step15test --> step16test
            step16test : Xray update
        }
    }

