# This workflow will update the webclient submodule on the supplied
# branch

name: Build assets

on:
  repository_dispatch:
    types: [build-assets]
  workflow_dispatch:
    inputs:
      tau_ref:
        default: ''
        description: 'tyk-analytics-ui tree-ish to use'
        required: true
  push:
    paths:
      - 'graphql/schema.graphql'
    branches:
      - 'as/manual-bindata'

env:
  SLACK_CLI_TOKEN: ${{ secrets.BENDER_TOKEN }}
  TAU_REF: ${{ github.event.client_payload.sha || github.event.inputs.tau_ref }}
  TA_REF: ${{ github.event.client_payload.ref }}

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout tyk-analytics/${{ github.event.client_payload.ref }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}

      - name: checkout tyk-analytics-ui/${{ github.event.client_payload.sha }}
        uses: actions/checkout@v2
        with:
          repository: TykTechnologies/tyk-analytics-ui
          token: ${{ secrets.ORG_GH_TOKEN }}
          path: webclient
          ref: ${{ env.TAU_REF }}

      - uses: actions/setup-go@v2
        with:
          go-version: 1.19.x
          
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
          
      - name: cache node modules
        uses: actions/cache@v1
        with:
          path: webclient/node_modules
          key: ${{ runner.os }}-nodemodules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nodemodules-
            ${{ runner.os }}-
            
      - name: Build webclient
        working-directory: ./webclient
        run: |
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          npm cache verify
          npm install --legacy-peer-deps
          npm rebuild node-sass
          npm run build
          echo $(git rev-parse HEAD) > ../.assets_vendor

      - name: Install go-bindata
        run: |
          go install github.com/shuLhan/go-bindata/v4/cmd/go-bindata@master
          
      - name: Generate bindata (release-1.9)
        if: ${{ contains(github.event.client_payload.ref, 'release-1.9') }}
        run: |
          go-bindata -o dashboard/bindata.go -pkg dashboard webclient/dist/...
          
      - name: Generate bindata (with graphql)
        if: ${{ ! contains(github.event.client_payload.ref, 'release-1.9') }}
        run: |
          go-bindata -o dashboard/bindata.go -pkg dashboard webclient/dist/... graphql/schema.graphql
          
      - name: Commit bindata and submodule
        run: |
          git config --local user.email "tip@tyk-analytics-ui"
          git config --local user.name "Bender"
          git add dashboard/bindata.go webclient
          git add -f .assets_vendor
          git commit -m "[CI] Adding assets from tyk-analytics-ui/${{ github.event.client_payload.ref }}/${{ github.event.client_payload.sha }}"
          git submodule update --remote --rebase

      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.bindata_deploy_key }}
          
      - name: Push changes
        id: push
        run: |
          git status
          git log HEAD..${{ env.TA_REF }}
          git pull --rebase --recurse-submodules=off origin ${{ env.TA_REF }}
          git remote set-url origin "$(git config --get remote.origin.url | sed 's#http.*com/#git@github.com:#g')"
          git push -v origin ${{ env.TA_REF }}

      - name: Notify status
        if: ${{ failure() }}
        run: |
          curl https://raw.githubusercontent.com/rockymadden/slack-cli/master/src/slack -o /tmp/slack && chmod +x /tmp/slack
          colour=bad
          pretext="Please review the workflow run and correct manually if required"
          /tmp/slack chat send \
          --actions '{"type": "button", "style": "primary", "text": "See log", "url": "https://github.com/TykTechnologies/tyk-analytics/actions/runs/${{ github.run_id }}"}' \
          --author 'Bender' \
          --author-icon 'https://hcoop.net/~alephnull/bender/bender-arms.jpg' \
          --author-link 'https://github.com/TykTechnologies/tyk-ci' \
          --channel '#dashboard' \
          --color bad \
          --fields '{"title": "Branch", "value": "${{ github.ref }}", "short": false}' \
          --footer 'github-actions' \
          --footer-icon 'https://assets-cdn.github.com/images/modules/logos_page/Octocat.png' \
          --image 'https://assets-cdn.github.com/images/modules/logos_page/Octocat.png' \
          --pretext "$pretext" \
          --text 'Failed building assets on `${{ env.TA_REF }}` for tyk-analytics-ui ref `${{ env.TAU_REF }}`' \
          --title 'Updating bindata.go' \
          --title-link 'https://github.com/TykTechnologies/tyk-analytics/actions/runs/${{ github.run_id }}'

