stateDiagram-v2
    workflow : ci-tests.yml - CI tests
    state workflow {
        golangci_lint: Golangci lint
        state golangci_lint {
            [*] --> step0golangci_lint
            step0golangci_lint : use gh token
            step0golangci_lint --> step1golangci_lint
            step1golangci_lint : Checkout Tyk Analytics
            step1golangci_lint --> step2golangci_lint
            step2golangci_lint : Download golangci-lint
            step2golangci_lint --> step3golangci_lint
            step3golangci_lint : golangci-lint
        }

        sonar_cloud_analysis: Sonar cloud analysis
        state sonar_cloud_analysis {
            [*] --> step0sonar_cloud_analysis
            step0sonar_cloud_analysis : Checkout Tyk Analytics
            step0sonar_cloud_analysis --> step1sonar_cloud_analysis
            step1sonar_cloud_analysis : Fetch base branch
            step1sonar_cloud_analysis --> step2sonar_cloud_analysis
            step2sonar_cloud_analysis : Setup Golang
            step2sonar_cloud_analysis --> step3sonar_cloud_analysis
            step3sonar_cloud_analysis : Download coverage artifacts
            step3sonar_cloud_analysis --> step4sonar_cloud_analysis
            step4sonar_cloud_analysis : Download golangcilint artifacts
            step4sonar_cloud_analysis --> step5sonar_cloud_analysis
            step5sonar_cloud_analysis : Check reports existence
            step5sonar_cloud_analysis --> step6sonar_cloud_analysis
            step6sonar_cloud_analysis : Install Dependencies
            step6sonar_cloud_analysis --> step7sonar_cloud_analysis
            step7sonar_cloud_analysis : merge reports
            step7sonar_cloud_analysis --> step8sonar_cloud_analysis
            step8sonar_cloud_analysis : SonarCloud Scan
        }

        test: ${{ matrix.databases }}
        state test {
            [*] --> step0test
            step0test : Checkout Tyk Analytics
            step0test --> step1test
            step1test : Checkout Tyk Analytics UI
            step1test --> step2test
            step2test : Setup Golang
            step2test --> step3test
            step3test : Cache
            step3test --> step4test
            step4test : Install Dependencies
            step4test --> step5test
            step5test : Fetch base branch
            step5test --> step6test
            step6test : ignore vendor and use go mod
            step6test --> step7test
            step7test : Start MongoDB
            step7test --> step8test
            step8test : Run Dashboard Tests
            step8test --> sonar-cloud-analysis
        }
    }

