stateDiagram-v2
    workflow : ui-tests.yml - UI Tests
    state workflow {
        test: Test
        state test {
            [*] --> step0test
            step0test : Install Node.js ${{ matrix.node-version }}
            step0test --> step1test
            step1test : Fix private module deps
            step1test --> step2test
            step2test : Set up Chrome with proper version
            step2test --> step3test
            step3test : Checkout of Dashboard
            step3test --> step4test
            step4test : Check if GW branch exists
            step4test --> step5test
            step5test : Checkout GW repository
            step5test --> step6test
            step6test : Check if test framework branch exists
            step6test --> step7test
            step7test : Checkout test repository
            step7test --> step8test
            step8test : start docker compose
            step8test --> step9test
            step9test : Install test dependecies
            step9test --> step10test
            step10test : Waiting for dashboard
            step10test --> step11test
            step11test : Execute UI tests
            step11test --> step12test
            step12test : Archive UI test report
            step12test --> step13test
            step13test : Slack notify
            step13test --> step14test
            step14test : Notify if custom notification failed
            step14test --> step15test
            step15test : Getting dashboard logs on failure
            step15test --> step16test
            step16test : Comment on PR
            step16test --> step17test
            step17test : Xray update
        }
    }

