stateDiagram-v2
    workflow : update-gomod.yml - Update go.mod
    state workflow {
        update: Update
        state update {
            [*] --> step0update
            step0update : checkout tyk-analytics/${{ github.event.client_payload.ref }}
            step0update --> step2update
            step2update : Fix Dependencies
            step2update --> step3update
            step3update : update go.mod
            step3update --> step4update
            step4update : Commit go.mod
            step4update --> step6update
            step6update : Push changes
            step6update --> step7update
            step7update : Notify status
        }
    }

