---
version: "3"

vars:
  cli: "go-fsck"

tasks:
  default:
    desc: "{{ .cli }}: Build, test, install"
    deps: [ fix ]
    cmds:
      - go install .
      - cmd: echo {{ .cli }} extract -i example/ -o example/go-fsck.json --pretty-json | sh -x
        silent: true
      - cmd: echo {{ .cli }} extract -i model/ -o model/go-fsck.json --pretty-json | sh -x
        silent: true

  test:
    desc: "Run go tests"
    cmds:
      - go test -count=100 -cover ./...

  restore:
    desc: "Restore from model"
    cmds:
      - cmd: echo {{ .cli }} restore -i model/go-fsck.json | sh -x
        silent: true

  fix:
    desc: "{{ .cli }}: Clean up source tree"
    aliases: ["fmt"]
    cmds:
      - goimports -w -local $(go list .) .
      - go fmt ./...
      - go mod tidy

  clean:
    desc: "{{ .cli}}: Clean build cache"
    cmds:
      - go clean -cache
