---
version: "3"

tasks:
  default:
    desc: "go-fsck: Build, test, install"
    deps: [ clean, fix ]
    cmds:
      - go install .
      - go-fsck extract -i example/ -o example/go-fsck.json --pretty-json
      - rm -rf model_restored && mkdir -p model_restored
      - go-fsck extract -i model/ -o model_restored/go-fsck.json --pretty-json
      - task: restore

  test:
    desc: "Run go tests"
    cmds:
      - go test -count=100 -cover ./...

  restore:
    desc: "Restore from model"
    dir: model_restored
    cmds:
      - go-fsck restore -p model --save
      - goimports -w .
      - go fmt .
      - go build .

  fix:
    desc: "go-fsck: Clean up source tree"
    aliases: ["fmt"]
    cmds:
      - goimports -w -local $(go list .) .
      - go fmt ./...
      - go mod tidy

  clean:
    desc: "{{ .cli}}: Clean model_restored"
    cmds:
      - rm -rf model_restored && mkdir model_restored
