---
version: "3"

tasks:
  default:
    desc: "go-fsck: Build, test, install"
    deps: [ clean, fix ]
    cmds:
      - go install .
      - rm -rf model/restored && mkdir -p model/restored
      - go-fsck extract --verbose --include-sources -i model/ -o model/restored/go-fsck.json --pretty-json
      - task: restore
      - task: example

  test:
    desc: "Run go tests"
    cmds:
      - go test -count=100 -cover ./...

  example:
    desc: "Build example"
    cmds:
      - go-fsck extract --verbose --include-tests --include-sources -i example/ -o example/go-fsck.json --pretty-json

  restore:
    desc: "Restore from model"
    dir: model/restored
    cmds:
      - go-fsck restore -p model --save --verbose
      - go-fsck restore -p model --stats-files | jq -s .
      - goimports -w .
      - go fmt .
      - go build .

  fix:
    desc: "go-fsck: Clean up source tree"
    aliases: ["fmt"]
    cmds:
      - goimports -w -local $(go list .) .
      - go fmt ./...
      - go mod tidy

  clean:
    desc: "{{ .cli}}: Clean model/restored"
    cmds:
      - rm -rf model/restored && mkdir model/restored

  stress:
    desc: "Stress test"
    cmds:
      - |-
        # Create a temporary file to store the results
        output_file=$(mktemp)

        # Run the command 100 times and store the results
        for i in {1..20}; do
          go-fsck extract --verbose --include-tests --include-sources -i example/ -o example/go-fsck.json | xargs md5sum >> "$output_file"
          go-fsck extract --include-sources -i model/ -o model/restored/go-fsck.json --pretty-json | xargs md5sum >> "$output_file"
        done

        # Count and display unique results with their occurrence count
        sort "$output_file" | uniq -c | sort -nr

        # Clean up the temporary file
        rm "$output_file"
