---
version: "3"

tasks:
  default:
    desc: "go-fsck: Build, test, install"
    deps: [ clean, fix ]
    cmds:
      - go install .
      - rm -rf model/restored && mkdir -p model/restored
      - go-fsck extract -i model/ -o model/restored/go-fsck.json --pretty-json
      - task: restore
      - task: example

  test:
    desc: "Run go tests"
    cmds:
      - go test -count=100 -cover ./...

  example:
    desc: "Build example"
    cmds:
      - go-fsck extract -i example/ -o example/go-fsck.json --pretty-json --include-tests


  restore:
    desc: "Restore from model"
    dir: model/restored
    cmds:
      - go-fsck restore -p model --save --verbose
      - go-fsck restore -p model --stats-files | jq -s .
      - goimports -w .
      - go fmt .
      - go build .

  fix:
    desc: "go-fsck: Clean up source tree"
    aliases: ["fmt"]
    cmds:
      - goimports -w -local $(go list .) .
      - go fmt ./...
      - go mod tidy

  clean:
    desc: "{{ .cli}}: Clean model/restored"
    cmds:
      - rm -rf model/restored && mkdir model/restored
