---
version: "3"

env:
  GOBIN: /usr/local/bin
  CGO_ENABLED: 0

tasks:
  default:
    desc: "Run default (install)"
    cmds:
      - task: install

  build:
    desc: "Build from source"
    deps: [fmt]
    cmds:
      - go build .

  install:
    desc: "Install from source"
    deps: [fmt]
    cmds:
      - go install .

  fmt:
    internal: true
    cmds:
      - goimports -w -local=$(go list .) .
      - go fmt ./...
      - go mod tidy

  docker:
    desc: "Build docker image"
    deps: [build]
    vars:
      image: internal/httpbin-logserver
    cmds:
      - docker build -t {{.image}} .
      - docker run --rm {{.image}} -? || true

  up:
    desc: "Bring up environment"
    cmds:
      - docker compose up -d --remove-orphans

  down:
    desc: "Bring down the environment"
    cmds:
      - docker compose down
