# yamllint disable rule:line-length rule:braces
---
version: "3"

vars:
  duration: 5

tasks:
  default:
    desc: "Ingest data for charts"
    vars:
      source: ../parse/output/
      limiters: 'drl rrl sentinel fixed-window sliding-window leaky-bucket token-bucket'
      outputs:
        sh: find {{.source}} -type f -name '*.json' | xargs -n1 basename
    cmds:
      - mkdir -p output
      - go fmt ./...
      - goimports -w .
      - for: { var: outputs, as: output }
        cmd: go run . -info -t rate -f {{.source}}{{.output}} -p {{.duration}}s -o output/{{.output | replace ".json" ".png"}}
        ignore_error: true
      - for: { var: limiters, as: kind }
        cmd: go run . -t duration -f {{.source}}{{.kind}}-rate-in.json -p {{.duration}}s -o output/{{.kind}}-latency.png
        ignore_error: true
      - for: { var: limiters, as: kind }
        cmd: go run . -t count -f {{.source}}{{.kind}}-rate-out.json -p {{.duration}}s -o output/{{.kind}}-requests.png
        ignore_error: true
