---
version: "3"

includes:
  services:
    taskfile: ../../docker/services/Taskfile.yml
    dir: ../../docker/services

tasks:
  default:
    desc: "Default"
    deps: [services:up]
    cmds:
      - defer: { task: services:down }
      - go fmt ./...
      - goimports -w .
      - go mod tidy
      - go test -count 1 -v ./...
