---
version: "3"

# Run as follows:
#
# - `task build` for latest/Dockerfile
# - `task release=5.0 build` for 5.0/Dockerfile
#
# Env parameters: `GITHUB_TAG`, `GITHUB_SHA` and `BUILD_PLATFORM`.
# All of them are optional. Git info is derived from the git
# checkout, and BUILD_PLATFORM defaults to linux/amd64.

vars:
  release: latest
  base: tykio/golang-cross:1.19-bullseye
  build: tykio/tyk-plugin-compiler
  tag: '{{.GITHUB_TAG | default "v5.1.0-dev"}}'
  sha: '{{.GITHUB_SHA | default "730d98024fda2a9fa9b3dddc6c4cc031813876ff"}}'
  platform: '{{.BUILD_PLATFORM | default "linux/amd64"}}'

env:
  DOCKER_BUILDKIT: 1
  BUILDX_EXPERIMENTAL: 1

tasks:
  build:
    desc: Build plugin compiler docker image
    cmds:
      - |
        docker build --rm \
        --platform {{.platform}} \
        --build-arg BASE_IMAGE={{.base}} \
        --build-arg=GITHUB_TAG={{.tag}} \
        --build-arg=GITHUB_SHA={{.sha}} \
        -t {{.build}}:{{.tag}} \
        -f {{.release}}/Dockerfile {{.release}}

  test:
    desc: "Test plugin compilation"
    cmds:
      - |
        docker run --platform {{.platform}} -e GITHUB_TAG={{.tag}} -e GITHUB_SHA={{.sha}} --rm -v $PWD/{{.release}}/data/basic-plugin/:/plugin-source {{.build}}:{{.tag}} basic.so

  sync:
    desc: "Sync changes from release branches"
    deps:
      - pull
    cmds:
      - rsync -a git/release-5.0.3/ci/images/plugin-compiler/ 5.0/
      - rsync -a git/release-5.1.1/ci/images/plugin-compiler/ 5.1/
      - rsync -a git/master/ci/images/plugin-compiler/ latest/

  checkout:
    desc: Checkout tyk repo branches
    cmds:
      - task: git:checkout
        vars: { branch: 'release-5.0.3' }
      - task: git:checkout
        vars: { branch: 'release-5.1.1' }
      - task: git:checkout
        vars: { branch: 'master' }

  pull:
    desc: "Git pull upstream repos"
    cmds:
      - task: git:pull
        vars: { branch: 'release-5.0.3' }
      - task: git:pull
        vars: { branch: 'release-5.1.1' }
      - task: git:pull
        vars: { branch: 'master' }

  status:
    desc: "Git status for upstream branches"
    aliases: ["st"]
    cmds:
      - task: git:status
        vars: { branch: 'release-5.0.3' }
      - task: git:status
        vars: { branch: 'release-5.1.1' }
      - task: git:status
        vars: { branch: 'master' }

  git:checkout:
    desc: "Git clone upstream repo {{.branch}}"
    internal: true
    silent: true
    status:
      - test -d git/{{.branch}}
    cmds:
      - git clone -b {{.branch}} --depth=1 https://github.com/TykTechnologies/tyk.git git/{{.branch}}

  git:pull:
    desc: "Git pull upstream repo {{.branch}}"
    internal: true
    deps:
      - git:checkout
    dir: git/{{.branch}}
    cmds:
      - git pull

  git:status:
    desc: "Git status upstream repo {{.branch}}"
    internal: true
    silent: true
    deps:
      - git:checkout
    dir: git/{{.branch}}
    cmds:
      - |
        echo Checkout: {{.branch}}
      - git branch
      - git status --porcelain
