# This workflow will run for all PRs opened against master

name: Test React

on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: actions/setup-node@v2
      with:
        node-version: '15.x'
    - uses: actions/cache@v2
      with:
        path: |
          node_modules
          ~/.npm
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
    - name: Fetch base branch
      if: ${{ github.event_name == 'pull_request' }}
      run: git fetch origin ${{ github.base_ref }}
    - name: install
      run: |
        npm config set //registry.npmjs.org/:_authToken "${{ secrets.NPM_TOKEN }}"
        npm install --legacy-peer-deps
        npm run test
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: .
        args: >
          -Dsonar.organization=tyktechnologies
          -Dsonar.projectKey=TykTechnologies_tyk-analytics-ui
          -Dsonar.sources=.
          -Dsonar.coverage.exclusions=**/tests/**
          -Dsonar.test.inclusions=**/tests/**
          -Dsonar.tests=.
          -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
    env:
      CI: true
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

