stateDiagram-v2
    workflow : ui-tests.yml - UI Tests
    state workflow {
        test: Test
        state test {
            [*] --> step0test
            step0test : Install Node.js ${{ matrix.node-version }}
            step0test --> step1test
            step1test : Set up Chrome with proper version
            step1test --> step2test
            step2test : Fix private module deps
            step2test --> step3test
            step3test : Check if test framework branch exists
            step3test --> step4test
            step4test : Checkout test repository
            step4test --> step5test
            step5test : Check if GW branch exists
            step5test --> step6test
            step6test : Checkout GW repository
            step6test --> step7test
            step7test : Check if Dashboard branch exists
            step7test --> step8test
            step8test : Checkout Dash repository
            step8test --> step9test
            step9test : Checkout of tyk-analytics-ui
            step9test --> step10test
            step10test : Build Dashboard UI
            step10test --> step11test
            step11test : start docker compose
            step11test --> step12test
            step12test : Install test dependecies
            step12test --> step13test
            step13test : Waiting for dashboard
            step13test --> step14test
            step14test : Execute UI tests
            step14test --> step15test
            step15test : Archive UI test report
            step15test --> step16test
            step16test : Slack notify
            step16test --> step17test
            step17test : Notify if custom notification failed
            step17test --> step18test
            step18test : Comment on PR
            step18test --> step19test
            step19test : Xray update
        }
    }

