# Keep the branch on tyk-analytics in sync with this branch

name: Trigger dashboard 

on:
  pull_request:
  push:
    branches:
      - master
      - release-**
      - integration/**
      - feature/**
      - bugfix/**

jobs:
  bindata:
    name: bindata.go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      
      - uses: actions/setup-node@v2
        with:
          node-version: '15.x'
          
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Build
        run: |
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          npm cache verify
          npm install --legacy-peer-deps
          npm rebuild node-sass
          npm run build

      - uses: peter-evans/repository-dispatch@v1
        if: github.event_name == 'push'
        with:
          token: ${{ secrets.ORG_GH_TOKEN }}
          repository: TykTechnologies/tyk-analytics
          event-type: build-assets
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
