---
version: "3"

vars:
  projects: tyk tyk-analytics tyk-analytics-ui tyk-docs exp

tasks:
  default:
    desc: "Update GitHub Actions"
    vars:
    cmds:
      - task: docs:sync
      - task: docs:gen

  clean:
    desc: "Clean git folders"
    cmds:
      - rm -rf git/*

  docs:fetch:
    desc: "Fetch projects"
    cmds:
      - mkdir -p git
      - for: { var: projects, as: project }
        task: git:clone
        vars:
          project: '{{.project}}'

  docs:sync:
    desc: "Sync GitHub worlflows"
    cmds:
      - for: { var: projects, as: project }
        silent: true
        cmd: |
             set -e
             echo {{.project}}
             mkdir {{.project}} -p
             rsync -a --del git/{{.project}}/.github/workflows/ ./{{.project}}/

  docs:gen:
    desc: "Generate docs"
    cmds:
      - for: { var: projects, as: project }
        task: report
        vars:
          project: '{{.project}}'

  report:
    internal: true
    require: [project]
    dir: '{{.project}}'
    cmds:
      - github-actions-viz -w --format md
      - github-actions-viz -w --format mermaid
      - rm *.yml *.yaml -f

  git:clone:
    internal: true
    require: [project]
    status:
      - type -d git/{{.project}}
    cmds:
      - git clone --depth=1 git@github.com:TykTechnologies/{{.project}}.git git/{{.project}}
