stateDiagram-v2
    workflow : codeql-analysis.yml - CodeQL
    state workflow {
        analyze: Analyze
        state analyze {
            [*] --> step0analyze
            step0analyze : Checkout repository
            step0analyze --> step2analyze
            step2analyze : Initialize CodeQL
            step2analyze --> step3analyze
            step3analyze : Autobuild
            step3analyze --> step4analyze
            step4analyze : Perform CodeQL Analysis
        }
    }

