---
version: "3"

tasks:
  default:
    desc: "Generate output docs"
    cmds:
      - goimports -w .
      - go mod tidy
      - go fmt ./...
      - go run main.go --exclude v3.0.0 > gateway-config.md