---
version: "3"

tasks:
  default:
    desc: "Lint/fmt and print help"
    deps:
      - fix
    cmds:
      - task -l

  fix:
    desc: "Fix source by running common sanitizers"
    silent: true
    cmds:
      - goimports -w .
      - go mod tidy
      - go fmt ./...
      - go vet ./...

  build:
    desc: "Build the Go project"
    deps:
      - fix
    cmds:
      - go install .
      - testjson

  test:
    desc: "Run tests for the Go project"
    cmds:
      - go test -race -cover ./...
      - task: build
      - testjson -i test-log.json > test-log.fixed.json
      - gotestsum --format dots-v2 --hide-summary skipped --raw-command -- cat task-log.fixed.json

  benchmark:
    desc: "Run benchmarks for the Go project"
    cmds:
      - go test -race -cover -benchmem -run=^$ -bench=".*" ./...
