stateDiagram-v2
    workflow : docsearch.yaml - Index update
    state workflow {
        index: Index
        state index {
            [*] --> step0index
            step0index : Index
        }
    }

