name: Test HTML
on:
  pull_request:

jobs:
  htmltest:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.111.3'
          extended: true
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0
      - name: Check broken links
        run: |
          cd tyk-docs
          sed -i "s|//tyk.io/docs/nightly/|/|" config.toml
          sed -i -E 's|//tyk\.io/docs/[0-9]+(\.[0-9]+)?/|/|g' config.toml
          sed -i "s|//tyk.io/docs/|/|" config.toml
          hugo
          cd ..
      - name: Run htmltest
        uses: wjdp/htmltest-action@master
        with:
          config: .htmltest.yml