stateDiagram-v2
    workflow : link-checker.yaml - Link Checker
    state workflow {
        link-checker: link-checker
        state link-checker {
            [*] --> step0link-checker
            step0link-checker : Setup Hugo
            step0link-checker --> step2link-checker
            step2link-checker : Check broken links
        }
    }

