stateDiagram-v2
    workflow : link-checker.yaml - Link Checker
    state workflow {
        link_checker: Link checker
        state link_checker {
            [*] --> step0link_checker
            step0link_checker : Setup Hugo
            step0link_checker --> step2link_checker
            step2link_checker : Check broken links
        }
    }

