stateDiagram-v2
    workflow : navigation-levels.yml - Check maximum nesting level is not exceeded
    state workflow {
        Check_max_levels: Check menu max levels
        state Check_max_levels {
            [*] --> step0Check_max_levels
            step0Check_max_levels : Checkout
            step0Check_max_levels --> step1Check_max_levels
            step1Check_max_levels : Set up Go
            step1Check_max_levels --> step2Check_max_levels
            step2Check_max_levels : Check navigation level does not exceed the defined maximum
        }
    }

