name: Check maximum nesting level is not exceeded
on: [pull_request]
env:
  MAX_LEVELS: 7

jobs:
  Check-max-levels:
    runs-on: ubuntu-20.04
    name: Check-menu-max-levels
    steps:

      # Checkout your code
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: "Check navigation level does not exceed the defined maximum"
        run: |
          cd scripts/navigation-levels
          go run main.go --max=$MAX_LEVELS
