stateDiagram-v2
    workflow : swagger-update.yaml - Tyk API documentation (OAS) sync
    state workflow {
        swagger_spec_update: Swagger spec update
        state swagger_spec_update {
            [*] --> step0swagger_spec_update
            step0swagger_spec_update : Checkout
            step0swagger_spec_update --> step1swagger_spec_update
            step1swagger_spec_update : Checkout gateway
            step1swagger_spec_update --> step2swagger_spec_update
            step2swagger_spec_update : Copy Swagger
            step2swagger_spec_update --> step3swagger_spec_update
            step3swagger_spec_update : Raise gateway swagger changes Pull Request
            step3swagger_spec_update --> step4swagger_spec_update
            step4swagger_spec_update : Checkout dashboard
            step4swagger_spec_update --> step5swagger_spec_update
            step5swagger_spec_update : Copy Swagger
            step5swagger_spec_update --> step6swagger_spec_update
            step6swagger_spec_update : Raise dashboard swagger changes Pull Request
        }
    }

