name: Linting
on: [pull_request]

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Vale
      uses: errata-ai/vale-action@master
      with:
        # Optional
        styles: |
          https://github.com/errata-ai/Microsoft/releases/latest/download/Microsoft.zip
          https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip

        # Optional
        config: https://raw.githubusercontent.com/TykTechnologies/tyk-docs/master/.github/workflows/.vale.ini

        # Optional
        files: __onlyModified
        onlyAnnotateModifiedLines: true
      env:
        # Required
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
