---
version: "3"

vars:
  coverage: test/allocator.cov
  cpuprofile: test/allocator.prof
  memprofile: test/allocator.mprof

tasks:
  default:
    desc: "Run everything"
    cmds:
      - task: fmt
      - task: test

  fmt:
    desc: "Run formatters"
    cmds:
      - goimports -w .
      - go fmt ./...
      - go-fsck docs ./allocator > allocator/README.md

  test:
    desc: "Build/run tests"
    cmds:
      - mkdir -p test
      - defer: rm -f allocator.test
      - go test -bench=. -benchtime=5s -benchmem -race -cpu 1,2,3 -cover -coverprofile {{.coverage}} -cpuprofile {{.cpuprofile}} -memprofile {{.memprofile}} -coverpkg=$(go list .) -v ./allocator

  cover:
    desc: "Show source coverage"
    aliases: [coverage, cov]
    cmds:
      - go tool cover -func={{.coverage}}

  uncover:
    desc: "Show uncovered source"
    cmds:
      - uncover {{.coverage}}
