---
version: '3'

tasks:
  default:
    name: "Run tool"
    cmds:
      - goimports -w .
      - go fmt .
      - go install .
      - task: example

  example:
    desc: "Build examples"
    dir: example
    cmds:
      - github-actions-viz -w --format md
      - github-actions-viz -w --format mermaid
