---
version: "3"

tasks:
  default:
    desc: "Extract docs"
    vars:
      releases:
        sh: task releases
    cmds:
      - rm -rf docs && mkdir -p docs
      - rm -rf schema && mkdir -p schema
      - for: { var: releases, as: release }
        cmd: task release={{.release}} extract:fsck
      - for: { var: releases, as: release }
        cmd: task release={{.release}} extract:schema

  extract:fsck:
    require: [ release ]
    desc: "Extract release info"
    cmds:
      - cd git/tyk && git checkout {{ .release }} && cd -
      - cd git/tyk-analytics && git checkout {{ .release }} && cd -
      - for: [ 'git/tyk', 'git/tyk-analytics' ]
        cmd: go-fsck extract -i git/tyk/config/ -o docs/{{ .ITEM | base }}-{{ .release }}-config.json --pretty-json
      - for: [ 'git/tyk' ]
        cmd: go-fsck extract -i git/tyk/apidef/ -o docs/{{ .ITEM | base }}-{{ .release }}-apidef.json --pretty-json
      - for: [ 'git/tyk' ]
        cmd: go-fsck extract -i git/tyk/apidef/oas/ -o docs/{{ .ITEM | base }}-{{ .release }}-oas.json --pretty-json

  extract:schema:
    require: [ release ]
    desc: "Extract release info"
    cmds:
      - cd git/tyk && git checkout {{ .release }} && cd -
      - cd git/tyk-analytics && git checkout {{ .release }} && cd -
      - for: [ 'git/tyk', 'git/tyk-analytics' ]
        cmd: schema-gen extract -i git/tyk/config/ -o schema/{{ .ITEM | base }}-{{ .release }}-config.json --pretty-json
      - for: [ 'git/tyk' ]
        cmd: schema-gen extract -i git/tyk/apidef/ -o schema/{{ .ITEM | base }}-{{ .release }}-apidef.json --pretty-json
      - for: [ 'git/tyk' ]
        cmd: schema-gen extract -i git/tyk/apidef/oas/ -o schema/{{ .ITEM | base }}-{{ .release }}-oas.json --pretty-json

  releases:
    desc: "Fetch release info from gateway"
    deps: [ git:checkout ]
    dir: git/tyk
    silent: true
    cmds:
      - git fetch --all -q
      - git ls-remote -q origin | grep refs/tags/v5 | grep -v '\-' | awk '{print $2}' | xargs -n1 basename

  git:checkout:
    desc: "Checkout the tyk repositories"
    status:
      - test -d git/tyk
      - test -d git/tyk-analytics
    ignore: true
    cmds:
      - git clone git@github.com:TykTechnologies/tyk.git git/tyk
      - git clone git@github.com:TykTechnologies/tyk-analytics.git git/tyk-analytics
