---
version: "3"

tasks:
  default:
    desc: "Extract data models from gateway"
    deps: [ install, tyk ]
    cmds:
      - mkdir -p apidef oas config

      - schema-gen extract -i tyk/apidef/ -o apidef/apidef.json
      - schema-gen extract -i tyk/config/ -o config/config.json
      - schema-gen extract -i tyk/apidef/oas/ -o oas/oas.json

      - schema-gen markdown -i apidef/apidef.json -o apidef/README.md --root APIDefinition
      - schema-gen markdown -i config/config.json -o config/README.md --root Config
      - schema-gen markdown -i oas/oas.json -o oas/README.md --root XTykAPIGateway

      - schema-gen restore -i apidef/apidef.json -o apidef/apidef.go -p apidef
      - schema-gen restore -i config/config.json -o config/config.go -p config
      - schema-gen restore -i oas/oas.json -o oas/oas.go -p oas

      - goimports -w -local github.com/TykTechnologies .

  lint:
    desc: "Lint the x-tyk-gateway OAS schema package"
    cmds:
      - schema-gen lint -i oas/oas.json

  tyk:
    internal: true
    status:
      - test -d tyk
    cmds:
      - git clone --depth=1 git@github.com:TykTechnologies/tyk.git

  install:
    desc: 'Install dependencies'
    deps:
      - install:schema-gen

  install:schema-gen:
    desc: 'Install schema-gen'
    status:
      - type schema-gen
    cmds:
      - go install github.com/TykTechnologies/exp/cmd/schema-gen@latest
