---
version: '3'

tasks:
  default:
    desc: "Run semgrep"
    deps: [pull]
    vars:
      absPath:
        sh: readlink -f .
    cmds:
      - docker run --rm -v {{.absPath}}/src:/src -v {{.absPath}}:/host semgrep/semgrep semgrep scan --metrics=off --config /host/rules/tyk/ --autofix --json -o /host/reports/semgrep.tyk.json || true

  debug:
    desc: "Run semgrep"
    deps: [pull]
    vars:
      absPath:
        sh: readlink -f .
    cmds:
      - docker run --rm -v {{.absPath}}/src:/src -v {{.absPath}}:/host semgrep/semgrep semgrep scan --verbose --metrics=off --config /host/rules/tyk/ --autofix --json -o /host/reports/semgrep.tyk.json 2>&1 | grep -v Ignoring
      - task: report

  report:
    desc: "Summarize semgrep report"
    cmds:
      - cat reports/semgrep.tyk.json | summary semgrep

  pull:
    desc: "Pull latest semgrep/semgrep"
    cmds:
      - docker pull semgrep/semgrep -q

  scan:
    desc: Scan with upstream rules
    vars:
      absPath:
        sh: readlink -f .
    cmds:
      - |
        docker run --rm -v {{.absPath}}/src:/src -v {{.absPath}}:/host semgrep/semgrep semgrep scan \
              --config /host/rules/ext-dgryski-semgrep-go/ \
              --autofix --json -o /host/reports/ext-dgryski-semgrep-go.json
      - |
        docker run --rm -v {{.absPath}}/src:/src -v {{.absPath}}:/host semgrep/semgrep semgrep scan \
              --config /host/rules/ext-semgrep-semgrep-rules/go/ \
               --autofix --json -o /host/reports/ext-semgrep-semgrep-rules.json

  semgrep:
    internal: true
    vars:
      output: rules/ext-semgrep-semgrep-rules
    status:
      - test -d {{.output}}
    cmds:
      - git clone --depth=1 https://github.com/semgrep/semgrep-rules {{.output}}

  semgrep-go:
    internal: true
    vars:
      output: rules/ext-dgryski-semgrep-go
    status:
      - test -d {{.output}}
    cmds:
      - git clone --depth=1 https://github.com/dgryski/semgrep-go {{.output}}
      - rm {{.output}}/ioutil.yml {{.output}}/oserrors.yml
