---
version: "3"

tasks:
  default:
    desc: Install dependencies for testing
    deps:
      - gocovmerge
      - gotestsum

  gocovmerge:
    internal: true
    status:
     - type gotestsum
    cmds:
      - |
        VERSION=v0.0.0-20160331181800-b5bfa59ec0ad
        go install github.com/wadey/gocovmerge@${VERSION}

  gotestsum:
    internal: true
    status:
      - type gotestsum
    cmds:
      - |
        VERSION=v1.12.3
        go install gotest.tools/gotestsum@${VERSION}
