---
version: "3"

tasks:
  all:
    desc: Install dependencies for testing
    deps:
      - install:gocovmerge
      - install:gotestsum

  install:gocovmerge:
    internal: true
    status:
     - type gotestsum
    cmds:
      - go install github.com/wadey/gocovmerge@latest

  install:gotestsum:
    internal: true
    status:
      - type gotestsum
    cmds:
      - go install gotest.tools/gotestsum@latest
