---
version: "3"

tasks:
  default:
    desc: Install dependencies for testing
    deps:
      - gocovmerge
      - gotestsum

  gocovmerge:
    internal: true
    status:
     - type gotestsum
    cmds:
      - go install github.com/wadey/gocovmerge@latest

  gotestsum:
    internal: true
    status:
      - type gotestsum
    cmds:
      - go install gotest.tools/gotestsum@latest
