name: Tyk master LTS acceptance test

on:
  workflow_dispatch:
    inputs:
      note:
        description: Note for run
        required: true
        default: ''
      branch:
        description: Branch to source
        required: true
        default: 'master'

env:
  GOPRIVATE: github.com/TykTechnologies

jobs:
  gateway:
    name: Gateway
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Gateway branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          repository: TykTechnologies/tyk
          ref: ${{ github.event.inputs.branch }}
          path: ./tyk

      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.16 # LTS (replace with golang-cross)

      - name: Source go.mod/sum from 5-lts
        dir: tyk
        run: |
          rm go.mod go.sum
          wget https://raw.githubusercontent.com/TykTechnologies/tyk/release-5-lts/go.mod
          wget https://raw.githubusercontent.com/TykTechnologies/tyk/release-5-lts/go.sum

      - name: Build LTS
        dir: tyk
        run: go build -tags=goplugin .
