name: Tyk cross-release build

on:
  workflow_dispatch:
    inputs:
      note:
        description: Note for run
        required: true
        default: ''
      branch:
        description: Branch to source
        required: true
        default: 'master'

env:
  GOPRIVATE: github.com/TykTechnologies

jobs:
  test-builds:
    name: 'Tags: ${{ matrix.tag }}'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag: [ 'v50', 'v50,v51', 'v50,v51,v52', 'v60' ]
        include:
          - tag: v50
            go-version: '1.16'
          - tag: v50,v51
            go-version: '1.19'
          - tag: v50,v51,v52
            go-version: '1.19'
          - tag: v60
            go-version: '1.20'

    steps:
      - name: Checkout of tyk
        uses: actions/checkout@v3
        with:
          repository: TykTechnologies/tyk
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 1

      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Reset go.mod/sum
        if: ${{ matrix.tag == 'v50' }}
        run: |
          rm go.mod go.sum
          wget https://raw.githubusercontent.com/TykTechnologies/tyk/release-5-lts/go.mod
          wget https://raw.githubusercontent.com/TykTechnologies/tyk/release-5-lts/go.sum

      - name: Build tests
        if: ${{ always() }}
        run: go test -c -tags '${{ matrix.tag }}' ./gateway

      - name: Build gateway
        if: ${{ always() }}
        run: go build -tags '${{ matrix.tag }}' .
