# yamllint disable rule:line-length
---
name: Modcheck

# This action runs modcheck to produce an automated upgrade PR.
# It holds some packages back due to the grep rules below in the modcheck_upgrade step.
# It will attempt to open a PR with the automated upgrades.

run-name: '[${{ inputs.jira }}] ${{ inputs.repository }}: ${{ github.actor }} running modcheck'

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      jira:
        description: 'JIRA ID (MM-NNNN or permalink)'
        required: true
        default: ''
      branch:
        description: 'Base branch'
        required: true
        default: 'master'
      goVersion:
        description: 'Go version'
        required: true
        default: '1.22.x'
      repository:
        description: 'Repository'
        type: choice
        options:
          - 'TykTechnologies/tyk'
          - 'TykTechnologies/tyk-analytics'
          - 'TykTechnologies/tyk-identity-broker'
          - 'TykTechnologies/storage'

env:
  GOPRIVATE: github.com/TykTechnologies

jobs:
  sanitize:
    name: Sanitize inputs
    runs-on: ubuntu-latest
    outputs:
      jira: ${{ steps.collect.outputs.jira }}
    steps:
      - name: Sanitize JIRA input
        id: collect
        run: |
          jira=$(echo '${{ github.event.inputs.jira }}' | sed -e 's/?.*//g' | xargs -n1 basename)
          if [ "$jira" == *"-"* ]; then
             echo "No valid JIRA ID found (no dash in JIRA ID)"
             exit 1
          fi
          echo "jira=$jira" >> $GITHUB_OUTPUT

  modcheck:
    runs-on: ubuntu-latest
    needs: [sanitize]

    steps:
      - name: Checkout PR
        uses: actions/checkout@v4.2.2
        with:
          token: ${{ secrets.ORG_GH_TOKEN }}

      - name: Set up env
        run: |
          echo "jira=${{ needs.sanitize.outputs.jira }}" >> $GITHUB_ENV
          echo "hold=gorm.io,PuerkitoBio/goquery,github.com/newrelic,go.opentelemetry.io,github.com/getkin/kin-openapi" >> $GITHUB_ENV
          echo "GOTOOLCHAIN=local" >> $GITHUB_ENV

      - name: Setup Golang
        uses: actions/setup-go@v5.2.0
        with:
          go-version: ${{ inputs.goVersion }}

      - name: 'Extract tykio/ci-tools:latest'
        uses: shrink/actions-docker-extract@v3.0.1
        with:
          image: tykio/ci-tools:latest
          path: /usr/local/bin/.
          destination: /usr/local/bin

      # Build and install modcheck
      - working-directory: ./cmd/modcheck
        run: task

      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          repository: ${{ github.event.inputs.repository }}
          token: ${{ secrets.ORG_GH_TOKEN }}
          ref: ${{ github.event.inputs.branch }}
          path: ./tyk

      - name: Install Dependencies
        env:
          TOKEN: '${{ secrets.ORG_GH_TOKEN }}'
        run: >
          git config --global url."https://${TOKEN}@github.com/TykTechnologies".insteadOf "https://github.com/TykTechnologies"

      - working-directory: ./tyk
        run: go mod download

      - working-directory: ./tyk
        id: modcheck
        run: |
          modcheck --for-upgrade --skip "${{ env.hold }}" | tee -a /tmp/modcheck.md

          echo 'report<<EOF' >> $GITHUB_OUTPUT
          cat /tmp/modcheck.md >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - working-directory: ./tyk
        id: modcheck_upgrade
        run: |
          modcheck --suggest --skip "${{ env.hold }}" | sh -x 2>&1 | tee -a /tmp/modcheck.log

          echo 'report<<EOF' >> $GITHUB_OUTPUT
          cat /tmp/modcheck.log >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - working-directory: ./tyk
        id: mod_tidy
        run: |
          go mod tidy | tee -a /tmp/go-mod.txt || true

          echo 'report<<EOF' >> $GITHUB_OUTPUT
          cat /tmp/go-mod.txt >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Raise PR
        uses: peter-evans/create-pull-request@v7.0.6
        with:
          token: ${{ secrets.ORG_GH_TOKEN }}
          commit-message: Import updated go.mod/go.sum
          title: '[${{ env.jira }}] [${{ github.event.inputs.branch }}] exp/modcheck: Update go.mod dependencies'
          body: |
            Triggered by: ${{ github.actor }}
            JIRA: https://tyktech.atlassian.net/browse/${{ env.jira }}

            ${{ steps.modcheck.outputs.report }}

            <details>
              <summary>Steps performed</summary>

              ~~~
              ${{ steps.modcheck_upgrade.outputs.report }}
              ~~~
            </details>

            <details>
              <summary>go mod tidy output</summary>

              ```
              ${{ steps.mod_tidy.outputs.report }}
              ```
            </details>

          branch: update/${{ env.jira }}/${{ github.event.inputs.branch }}-update-go-mod
          path: ./tyk
          delete-branch: true
