# yamllint disable rule:line-length
---
name: Semgrep

# The intent of the action is two fold:
#
# - Scan repositories for violations
# - Heal existing state with semgrep refactoring rules
#
# It's a way to enforce small patterns for consistency, bug avoidance,
# and other purposes aimed at style and stability.
#
# For local development:
# - navigate to lsc/semgrep/
# - check out repository under `src`
# - run `task`

run-name: '[${{ inputs.jira }}] ${{ inputs.repository }}: ${{ github.actor }} running semgrep'

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      jira:
        description: 'JIRA ID (MM-NNNN or permalink)'
        required: true
        default: ''
      branch:
        description: 'Base branch'
        required: true
        default: 'master'
      repository:
        description: 'Repository'
        type: choice
        options:
          - 'TykTechnologies/tyk'
          - 'TykTechnologies/tyk-analytics'

env:
  GOPRIVATE: github.com/TykTechnologies

jobs:
  sanitize:
    name: Sanitize inputs
    runs-on: ubuntu-latest
    outputs:
      jira: ${{ steps.collect.outputs.jira }}
    steps:
      - name: Sanitize JIRA input
        id: collect
        run: |
          jira=$(echo '${{ github.event.inputs.jira }}' | sed -e 's/?.*//g' | xargs -n1 basename)
          if [ "$jira" == *"-"* ]; then
             echo "No valid JIRA ID found (no dash in JIRA ID)"
             exit 1
          fi
          echo "jira=$jira" >> $GITHUB_OUTPUT

  semgrep:
    runs-on: ubuntu-latest
    needs: [sanitize]

    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ORG_GH_TOKEN }}

      - name: Set up env
        run: |
          echo "jira=${{ needs.sanitize.outputs.jira }}" >> $GITHUB_ENV

      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'

      - name: 'Extract tykio/ci-tools:latest'
        uses: shrink/actions-docker-extract@v3
        with:
          image: tykio/ci-tools:latest
          path: /usr/local/bin/.
          destination: /usr/local/bin

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.repository }}
          token: ${{ secrets.ORG_GH_TOKEN }}
          ref: ${{ github.event.inputs.branch }}
          path: ./lsc/semgrep/src

      - name: Install Dependencies
        env:
          TOKEN: '${{ secrets.ORG_GH_TOKEN }}'
        run: >
          git config --global url."https://${TOKEN}@github.com/TykTechnologies".insteadOf "https://github.com/TykTechnologies"

      - working-directory: ./lsc/semgrep
        id: semgrep
        run: |
          task | tee -a /tmp/semgrep.md

          echo 'report<<EOF' >> $GITHUB_OUTPUT
          cat /tmp/semgrep.md >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Raise PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.ORG_GH_TOKEN }}
          commit-message: Semgrep scan result
          title: '[${{ env.jira }}] exp/semgrep: Update from LSC semgrep rule'
          body: |
            Triggered by: ${{ github.actor }}

            ~~~
            ${{ steps.semgrep.outputs.report }}
            ~~~

            JIRA: https://tyktech.atlassian.net/browse/${{ env.jira }}
          branch: update/${{ env.jira }}/semgrep-check
          path: ./lsc/semgrep/src
          delete-branch: true
